# Generated by Django 3.1 on 2020-09-03 10:14

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('二级标题', streams.blocks.SecondLevelTitleBlock(help_text='二级标题', max_length=100)), ('新闻图片', streams.blocks.ImageChooserBlock(help_text='新闻图片')), ('正文段落', streams.blocks.MainTextBlock(help_text='正文段落'))], blank=True, null=True),
        ),
    ]
