# Generated by Django 3.1.1 on 2020-09-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('news', '0002_auto_20200903_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsListingListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': '栏目页',
                'verbose_name_plural': '栏目页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='newsdetailpage',
            options={'verbose_name': '文章内容页', 'verbose_name_plural': '文章内容页'},
        ),
        migrations.AlterModelOptions(
            name='newslistingpage',
            options={'verbose_name': '文章列表页', 'verbose_name_plural': '文章列表页'},
        ),
    ]
