# Generated by Django 3.1.1 on 2020-09-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('news', '0003_auto_20200905_0512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsListingListingPage',
        ),
    ]
