# Generated by Django 3.1.1 on 2020-09-06 12:54

from django.db import migrations, models
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_newslistinglistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetailpage',
            name='is_taotiao',
            field=models.BooleanField(default=False, verbose_name='是否头条'),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('二级标题', streams.blocks.SecondLevelTitleBlock(help_text='二级标题', max_length=100)), ('新闻图片', streams.blocks.ImageChooserBlock(help_text='新闻图片')), ('正文段落', streams.blocks.MainTextBlock(help_text='正文段落'))], blank=True, null=True, verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='news_title',
            field=models.CharField(help_text='新闻标题', max_length=100, verbose_name='新闻标题'),
        ),
    ]
